"""empty message

Revision ID: b4925a8aa587
Revises: 8e47eb94a9b9
Create Date: 2021-05-02 17:20:43.544640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4925a8aa587'
down_revision = '8e47eb94a9b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'order_date',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('orders_mail_key', 'orders', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('orders_mail_key', 'orders', ['mail'])
    op.alter_column('orders', 'order_date',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
