"""empty message

Revision ID: 9d8d5786f63c
Revises: 199d6840d7bf
Create Date: 2021-05-15 21:39:21.744165

"""
import sqlalchemy as sa
from alembic import op
from food_delivery.models import OrderStatusType
from sqlalchemy_utils import ChoiceType

# revision identifiers, used by Alembic.
revision = '9d8d5786f63c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('title'),
                    sa.UniqueConstraint('title')
                    )
    op.create_table('dishes',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.Column('price', sa.Integer(), nullable=True),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('picture', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('password_hash', sa.String(), nullable=False),
                    sa.Column('is_admin', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('email')
                    )
    op.create_table('categories_dishes',
                    sa.Column('category_id', sa.Integer(), nullable=True),
                    sa.Column('dish_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
                    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], )
                    )
    op.create_table('orders',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('date', sa.DateTime(), nullable=False),
                    sa.Column('total', sa.Integer(), nullable=False),
                    sa.Column('status', ChoiceType(OrderStatusType), default='New'),
                    sa.Column('phone', sa.String(length=15), nullable=False),
                    sa.Column('address', sa.String(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('orders_dishes',
                    sa.Column('order_id', sa.Integer(), nullable=True),
                    sa.Column('dish_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ),
                    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], )
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders_dishes')
    op.drop_table('orders')
    op.drop_table('categories_dishes')
    op.drop_table('users')
    op.drop_table('dishes')
    op.drop_table('categories')
    # ### end Alembic commands ###
